name = "radiate"
version = "0.4.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Hot reloading while in development for Gleam"
licences = ["Apache-2.0"]
repository = {type = "github", user = "pta2002", repo = "gleam-radiate"}
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
filespy = { git = "https://github.com/h22roscoe/gleam-filespy.git", ref = "76a1562bbd950728bae4258ad3a19072158b8291" }
gleam_erlang = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"
